name: aerospike-client-rest


container:
  - base:
      - docker.qe.aerospike.com/build/aerospike-client-rest:openjdk-8

build:
  - name: build
    script:
      - source ~/.bashrc
      - make package
    artifact:
      - ./target/*.tgz

